server
{
    Name    server
    Port    1234
    Host    127.0.0.3

    Client-max-body-size    20480000
    error_page 400 html/400.html
    error_page 403 html/403.html
    error_page 404 html/404.html
    error_page 405 html/405.html
    error_page 413 html/413.html
    error_page 500 html/500.html
    
    route
    {
        Allowed GET POST DELETE
        Match   /truc
        Location    html/
        Listing index.html
    }

    route
    {
        Allowed GET
        Forbidden DELETE POST
        Match   /truc/machin
        Location    htmlcopy/
        Listing OFF
    }

    route
    {
        Allowed GET
        Match   /
        Location    html/
        Listing welcome.html   
    }
}
server
{
    Name    autre
    Port    1234
    Host 127.0.0.4
    Client-max-body-size    1024

    route
    {
        Allowed GET
        Match /
        Location html2/
        Listing OFF
    }

    route
    {
        Allowed GET
        Allowed POST
        Forbidden DELETE
        Match   /autre
        Location    html/
        Listing OFF
        Cgi-pass    .php    /bin/php-cgi
        Cgi-pass    .py     /bin/python
    }
}
